-- تحديد قاعدة البيانات لاستخدامها
USE alx_book_store;

-- إنشاء جدول authors
CREATE TABLE AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE,
    NATIONALITY VARCHAR(100)
);

-- إنشاء جدول books
CREATE TABLE BOOKS (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    GENRE VARCHAR(100),
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK_QUANTITY INT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- إنشاء جدول customers
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    ADDRESS TEXT
);

-- إنشاء جدول orders
CREATE TABLE
